export const Config = {
  // SOLANA_PROGRAM_ID: 'HPMuRYYkN7XovdWwgPWL23BmbLktoj1ge3nAKyeZcFTg',
  // SOLANA_CURVE_CONFIG_ADDRESS: '9Vy2eKdoAsFmUy9ZvFw7b9KxnHuGh44239TdcMPinNpM',
  // SOLANA_PROTOCOL_ACCOUNT_ADDRESS: 'C4hLmsUjFmRL3YXjZBYwpA9qJbtZSTY3ZkeVTP6TGnA5',
};